AWSTemplateFormatVersion: '2010-09-09'
Description: 'Notes with Sentiment - Backend Infrastructure'

Resources:
  # DynamoDB Table
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Notes-CDK
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sentiment
          AttributeType: S
        - AttributeName: dateCreated
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: SentimentIndex
          KeySchema:
            - AttributeName: sentiment
              KeyType: HASH
            - AttributeName: dateCreated
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # AppSync GraphQL API
  NotesApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: notes-sentiment-api-cdk
      AuthenticationType: API_KEY
      XrayEnabled: false

  # GraphQL Schema
  NotesApiSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt NotesApi.ApiId
      Definition: |
        type Note {
            id: ID!
            text: String!
            sentiment: Sentiment!
            dateCreated: AWSDateTime!
        }

        type NoteQueryResults {
            items: [Note]
            nextToken: String
            scannedCount: Int
        }

        enum Sentiment {
            happy
            sad
            neutral
            angry
        }

        type Mutation {
            createNote(text: String!, sentiment: Sentiment!): Note
        }

        type Query {
            getNotes(sentiment: Sentiment, limit: Int, nextToken: String): NoteQueryResults
        }

  # API Key
  NotesApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt NotesApi.ApiId
      Description: API Key for Notes with Sentiment API
      Expires: 1796438010
    DependsOn: NotesApiSchema

  # IAM Role for DynamoDB Data Source
  NotesDataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:DeleteItem
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - !GetAtt NotesTable.Arn
                  - !Sub "${NotesTable.Arn}/index/*"

  # DynamoDB Data Source
  NotesDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt NotesApi.ApiId
      Name: NotesDynamoDBDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt NotesDataSourceRole.Arn
      DynamoDBConfig:
        TableName: !Ref NotesTable
        AwsRegion: !Ref AWS::Region

  # CreateNote Resolver
  CreateNoteResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt NotesApi.ApiId
      TypeName: Mutation
      FieldName: createNote
      DataSourceName: !GetAtt NotesDataSource.Name
      Kind: UNIT
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($util.autoUlid())
          },
          "attributeValues": {
            "text": $util.dynamodb.toDynamoDBJson($ctx.args.text),
            "sentiment": $util.dynamodb.toDynamoDBJson($ctx.args.sentiment),
            "dateCreated": $util.dynamodb.toDynamoDBJson($util.time.nowISO8601())
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
    DependsOn:
      - NotesDataSource
      - NotesApiSchema

  # GetNotes Resolver
  GetNotesResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt NotesApi.ApiId
      TypeName: Query
      FieldName: getNotes
      DataSourceName: !GetAtt NotesDataSource.Name
      Kind: UNIT
      RequestMappingTemplate: |
        #set($limit = 10)
        #if($ctx.args.limit)
          #set($limit = $ctx.args.limit)
        #end

        #if($ctx.args.sentiment)
          ## Use GSI query for efficient sentiment filtering
          {
            "version": "2017-02-28",
            "operation": "Query",
            "index": "SentimentIndex",
            "query": {
              "expression": "sentiment = :sentiment",
              "expressionValues": {
                ":sentiment": $util.dynamodb.toDynamoDBJson($ctx.args.sentiment)
              }
            },
            "scanIndexForward": false,
            "limit": $limit,
            #if($ctx.args.nextToken)
              "nextToken": "$ctx.args.nextToken"
            #end
          }
        #else
          ## Use scan for all notes
          {
            "version": "2017-02-28",
            "operation": "Scan",
            "limit": $limit,
            #if($ctx.args.nextToken)
              "nextToken": "$ctx.args.nextToken"
            #end
          }
        #end
      ResponseMappingTemplate: |
        {
          "items": [
            #foreach($item in $ctx.result.items)
            {
              "id": "$item.id",
              "text": "$item.text",
              "dateCreated": "$item.dateCreated",
              "sentiment": "#if($item.sentiment)$item.sentiment.toLowerCase()#else$item.sentiment#end"
            }#if($foreach.hasNext),#end
            #end
          ],
          "nextToken": #if($ctx.result.nextToken)"$ctx.result.nextToken"#else null #end,
          "scannedCount": #if($ctx.result.scannedCount)$ctx.result.scannedCount #else 0 #end
        }
    DependsOn:
      - NotesDataSource
      - NotesApiSchema

# Outputs
Outputs:
  GraphQLApiEndpoint:
    Description: GraphQL API endpoint
    Value: !GetAtt NotesApi.GraphQLUrl
    Export:
      Name: !Sub ${AWS::StackName}-GraphQLApiEndpoint

  GraphQLApiKey:
    Description: GraphQL API key
    Value: !GetAtt NotesApiKey.ApiKey
    Export:
      Name: !Sub ${AWS::StackName}-GraphQLApiKey

  GraphQLApiId:
    Description: GraphQL API ID
    Value: !GetAtt NotesApi.ApiId
    Export:
      Name: !Sub ${AWS::StackName}-GraphQLApiId

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref NotesTable
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDBTableName

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
    Export:
      Name: !Sub ${AWS::StackName}-Region